import java.awt.EventQueue;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.Font;
import java.awt.Image;

import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;

public class Main extends javax.swing.JFrame {
	/*
	 * Title: Main Class
	 * Author: Arda Baran
	 * Description: This class serves as the entry point for running the program with a graphical user interface (GUI).
	 */
    /**
     * Creates new form Main
     */
    public Main() {
    	setIconImage(Toolkit.getDefaultToolkit().getImage(Main.class.getResource("/resources/images/eye.png")));
    	
    	
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        String selectedTC;
        tcGsmPanel = new javax.swing.JTabbedPane();
        nameSurnamePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameJTF = new javax.swing.JTextField();
        surnameJTF = new javax.swing.JTextField();
        nameSurnameSearchButton = new javax.swing.JButton();
        nameSurnameSearchButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        String name = nameJTF.getText();
        String surname=surnameJTF.getText();
        if (name.isEmpty() || surname.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(null, "Lütfen hem isim hem de soyisim giriniz.");
            return;
        }

        QueryHelper queryHelperNameSurname = new QueryHelper();

        try {
           
            queryHelperNameSurname.getCitiziensByNameSurname(name, surname);

            
            List<Citizien> results = queryHelperNameSurname.getSearchByNameSurnameResults();
            DefaultTableModel model = (DefaultTableModel) nameSurnameJTable.getModel();
            model.setRowCount(0); 

            for (Citizien citizien : results) {
                Object[] row = {
                    citizien.getId(),
                    citizien.getTc(),
                    citizien.getName(),
                    citizien.getSurname(),
                    citizien.getBirthDate(),
                    citizien.getCity(),
                    citizien.getCounty(),
                    citizien.getMotherName(),
                    citizien.getMotherTc(),
                    citizien.getFatherName(),
                    citizien.getFatherTc(),
                    citizien.getNationality()
                };
                model.addRow(row);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(null, "Veritabanına erişim sırasında bir hata oluştu.");
        }
    }
});	
        	
        
        
        
        
        jScrollPane1 = new javax.swing.JScrollPane();
        nameSurnameJTable = new javax.swing.JTable();
        nameSurnameJTable.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
                int row = nameSurnameJTable.getSelectedRow();
                int column = nameSurnameJTable.getSelectedColumn();

                
                if (column == 1 && row != -1) {
                    String getcFromNameSurname = nameSurnameJTable.getValueAt(row, column).toString();
                    try {
                        Citizien selectedCitizen = Citizien.getCitizenByTc(getcFromNameSurname);
                        selectedCitizen.findFamilyMembers();
                        selectedCitizen.findPhoneNumbers();
                        selectedCitizen.findAdresses();
                        if (selectedCitizen != null) {
                            CitizienInfoForm citizenInfoForm = new CitizienInfoForm(selectedCitizen);
                            citizenInfoForm.setVisible(true);
                        }
                    } catch (SQLException ex) {
                        ex.printStackTrace(); 
                        
                    }
                }
            }
        });
        tcPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tcJTF = new javax.swing.JTextField();
        tcSearchButton = new javax.swing.JButton();
        tcSearchButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        String tckn = tcJTF.getText();
        if (tckn.isEmpty() ) {

            javax.swing.JOptionPane.showMessageDialog(null, "Lütfen TC Numarasını Giriniz.");
            return;
        } 
        
        
        
        try {
            Citizien foundCitizien = Citizien.getCitizenByTc(tckn);
            foundCitizien.findFamilyMembers();
            foundCitizien.findPhoneNumbers();
            foundCitizien.findAdresses();
            if (foundCitizien != null) {
                CitizienInfoForm citizenInfoFormForTckn = new CitizienInfoForm(foundCitizien);
                citizenInfoFormForTckn.setVisible(true);
            }
        } catch (SQLException ex) {
            ex.printStackTrace(); 
            
        }   	
        	
        	
        	
        	
        	
        	}
        });
        gsmPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        gsmJTF = new javax.swing.JTextField();
        gsmSearchButton = new javax.swing.JButton();
        gsmSearchButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        String gsmNo = gsmJTF.getText();
        if (gsmNo.isEmpty() ) {

            javax.swing.JOptionPane.showMessageDialog(null, "Lütfen GSM Numarasını Giriniz.");
            return;
        }
        
        QueryHelper queryHelperGsm = new QueryHelper();
        try {
            
        	queryHelperGsm.searchGsmNumber(gsmNo);

            
            List<String> gsmtcResult = new ArrayList<>(queryHelperGsm.getGsmNumberRegisteredTCNumbers());
            DefaultListModel listModel = new DefaultListModel();
            for (int i = 0; i < gsmtcResult.size(); i++)
            {
                listModel.addElement(gsmtcResult.get(i));
            }
            
            gsmTCJlist.setModel(listModel);
        } catch (SQLException ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(null, "Veritabanına erişim sırasında bir hata oluştu.");
        }	
        
        
        	}
        });
        jScrollPane3 = new javax.swing.JScrollPane();
        gsmTCJlist = new javax.swing.JList<>();
        gsmTCJlist.addListSelectionListener(new ListSelectionListener() {
        	public void valueChanged(ListSelectionEvent e) {
        	}
        });
        jLabel5 = new javax.swing.JLabel();
        gsmTCSearchButton = new javax.swing.JButton();
        gsmTCSearchButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	String selectedTC = gsmTCJlist.getSelectedValue();
        	 try {
                 Citizien selectedTCFromGsmList = Citizien.getCitizenByTc(selectedTC);
                 selectedTCFromGsmList.findFamilyMembers();
                 selectedTCFromGsmList.findPhoneNumbers();
                 selectedTCFromGsmList.findAdresses();
                 if (selectedTCFromGsmList != null) {
                     CitizienInfoForm citizenInfoFormForGsmTckn = new CitizienInfoForm(selectedTCFromGsmList);
                     citizenInfoFormForGsmTckn.setVisible(true);
                 }
             } catch (SQLException ex) {
                 ex.printStackTrace(); 
                 
             }   	
        	
        	}
        });
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tcGsmTF = new javax.swing.JTextField();
        tcGsmSearchButton = new javax.swing.JButton();
        tcGsmSearchButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	String tckNo = tcGsmTF.getText();
        	 QueryHelper queryHelperTcGsm = new QueryHelper();
             try {
                 
            	 queryHelperTcGsm.findGsmNumbersRegisteredToTc(tckNo);

                 
                 List<String> tcgsmResult = new ArrayList<>(queryHelperTcGsm.getGsmNumberBelongToTCNumber());
                 DefaultListModel listModel = new DefaultListModel();
                 for (int i = 0; i < tcgsmResult.size(); i++)
                 {
                     listModel.addElement(tcgsmResult.get(i));
                 }
                 
                 tcGsmJlist.setModel(listModel);
             } catch (SQLException ex) {
                 ex.printStackTrace();
                 javax.swing.JOptionPane.showMessageDialog(null, "Veritabanına erişim sırasında bir hata oluştu.");
             }	
        	
        	}
        });
        jScrollPane2 = new javax.swing.JScrollPane();
        tcGsmJlist = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BaranPanel");

        jLabel1.setText("ADI:");

        jLabel2.setText("SOYADI:");

        nameSurnameSearchButton.setText("SORGULA");

        nameSurnameJTable.setFont(new Font("Segoe UI", Font.PLAIN, 10)); // NOI18N
        nameSurnameJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "TC", "ADI", "SOYADI", "DOĞUM TARİHİ", "NÜFUS İL", "NÜFUS İLÇE", "ANNE ADI", "ANNE TC", "BABA ADI", "BABA TC", "UYRUK"
            }
        ));
        jScrollPane1.setViewportView(nameSurnameJTable);
      
        javax.swing.GroupLayout nameSurnamePanelLayout = new javax.swing.GroupLayout(nameSurnamePanel);
        nameSurnamePanel.setLayout(nameSurnamePanelLayout);
        nameSurnamePanelLayout.setHorizontalGroup(
            nameSurnamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameSurnamePanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(nameSurnamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameSurnameSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(nameSurnamePanelLayout.createSequentialGroup()
                        .addGroup(nameSurnamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nameSurnamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameJTF)
                            .addComponent(surnameJTF, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))))
                .addContainerGap(418, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameSurnamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        nameSurnamePanelLayout.setVerticalGroup(
            nameSurnamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameSurnamePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(nameSurnamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(nameSurnamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(surnameJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(nameSurnameSearchButton)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );

        tcGsmPanel.addTab("ADI SOYADI İLE SORGULAMA", nameSurnamePanel);

        jLabel3.setText("TC NO:");

        tcSearchButton.setText("SORGULA");

        javax.swing.GroupLayout tcPanelLayout = new javax.swing.GroupLayout(tcPanel);
        tcPanel.setLayout(tcPanelLayout);
        tcPanelLayout.setHorizontalGroup(
            tcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tcPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tcSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addComponent(tcJTF))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        tcPanelLayout.setVerticalGroup(
            tcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tcPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(tcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(46, 46, 46)
                .addComponent(tcSearchButton)
                .addContainerGap(332, Short.MAX_VALUE))
        );

        tcGsmPanel.addTab("TC NUMARASI İLE SORGULAMA", tcPanel);

        jLabel4.setText("GSM NO:");

        gsmSearchButton.setText("SORGULA");

        jScrollPane3.setViewportView(gsmTCJlist);

        jLabel5.setText("Hattın Ait Olduğu Kişilerin TC Numaraları:");

        gsmTCSearchButton.setText("SEÇİLEN TC NUMARASINI SORGULA");

        javax.swing.GroupLayout gsmPanelLayout = new javax.swing.GroupLayout(gsmPanel);
        gsmPanel.setLayout(gsmPanelLayout);
        gsmPanelLayout.setHorizontalGroup(
            gsmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gsmPanelLayout.createSequentialGroup()
                .addGroup(gsmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gsmPanelLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gsmPanelLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(gsmSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gsmPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gsmJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gsmPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gsmPanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(gsmTCSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        gsmPanelLayout.setVerticalGroup(
            gsmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gsmPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(gsmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(gsmJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(gsmSearchButton)
                .addGap(49, 49, 49)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(gsmTCSearchButton)
                .addContainerGap())
        );

        tcGsmPanel.addTab("GSM NUMARASI SORGULAMA", gsmPanel);

        jLabel6.setText("TC NO:");

        tcGsmSearchButton.setText("SORGULA");

        jScrollPane2.setViewportView(tcGsmJlist);

        jLabel7.setText("Kişinin Üzerine Kayıtlı GSM Numaraları:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(tcGsmSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tcGsmTF))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(414, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tcGsmTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(tcGsmSearchButton)
                .addGap(53, 53, 53)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
          
        tcGsmPanel.addTab("TC İLE GSM SORGULAMA", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tcGsmPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(tcGsmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        
        JPanel panel = new JPanel();
        tcGsmPanel.addTab("VERGİ NO VE İKAMETGAH SORGULAMA", null, panel, null);
        panel.setLayout(null);
        
        JLabel lblNewLabel = new JLabel("TC NO:");
        lblNewLabel.setBounds(10, 56, 138, 13);
        panel.add(lblNewLabel);
        
        vergiAdressTCJtf = new JTextField();
        vergiAdressTCJtf.setFont(new Font("Tahoma", Font.PLAIN, 12));
        vergiAdressTCJtf.setBounds(146, 53, 436, 28);
        panel.add(vergiAdressTCJtf);
        vergiAdressTCJtf.setColumns(10);
        
        JButton vergiAdressButton = new JButton("SORGULA");
        vergiAdressButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	String tcknTaxAdress = vergiAdressTCJtf.getText();
        	QueryHelper taxAndAdress = new QueryHelper();
        	try {
        		taxAndAdress.getTaxAndAdressRecordsOfCitizien(tcknTaxAdress);
        	List <TaxAndAddressQueryHelper> taxAndAddressRecords = taxAndAdress.getTaxNumbersAndAdresses();
            DefaultTableModel model1 = (DefaultTableModel) vergiAddressJtable.getModel();
            model1.setRowCount(0); 

            for (TaxAndAddressQueryHelper at : taxAndAddressRecords) {
                Object[] row = {
         at.getTckn(),
         at.getNameSurname(),
         at.getBirthPlace(),
         at.getTaxNo(),
         at.getAdress()
         
                };
                model1.addRow(row);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(null, "Veritabanına erişim sırasında bir hata oluştu.");
        }
        	
        	}
        			
        	
        });
        vergiAdressButton.setBounds(146, 127, 436, 35);
        panel.add(vergiAdressButton);
        
        JScrollPane scrollPane = new JScrollPane();
        scrollPane.setBounds(22, 245, 931, 210);
        panel.add(scrollPane);
        
        vergiAddressJtable = new JTable();
        vergiAddressJtable.setModel(new DefaultTableModel(
        	new Object[][] {
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        	},
        	new String[] {
        		"TC", "ADI SOYADI", "DOĞUM TARİHİ", "VERGİ NUMARASI", "IKAMETGAH"
        	}
        ));
        scrollPane.setViewportView(vergiAddressJtable);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField gsmJTF;
    private javax.swing.JPanel gsmPanel;
    private javax.swing.JButton gsmSearchButton;
    private javax.swing.JList<String> gsmTCJlist;
    private javax.swing.JButton gsmTCSearchButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nameJTF;
    private javax.swing.JTable nameSurnameJTable;
    private javax.swing.JPanel nameSurnamePanel;
    private javax.swing.JButton nameSurnameSearchButton;
    private javax.swing.JTextField surnameJTF;
    private javax.swing.JList<String> tcGsmJlist;
    private javax.swing.JTabbedPane tcGsmPanel;
    private javax.swing.JButton tcGsmSearchButton;
    private javax.swing.JTextField tcGsmTF;
    private javax.swing.JTextField tcJTF;
    private javax.swing.JPanel tcPanel;
    private javax.swing.JButton tcSearchButton;
    private JTextField vergiAdressTCJtf;
    private JTable vergiAddressJtable;
}